-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 15:35:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_main` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_main` ;

-- -----------------------------------------------------
-- Table `db_main`.`Klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Klient` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Klient` (
  `IdKlient` INT NOT NULL,
  `Adres` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Nazwa` VARCHAR(45) NULL,
  `NIP` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`IdKlient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Modele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Modele` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Modele` (
  `IdModele` INT NOT NULL,
  `Marka` VARCHAR(45) NULL DEFAULT NULL,
  `Model` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdModele`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Auto` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Auto` (
  `IdAuto` INT NOT NULL,
  `Modele_IdModele` INT NOT NULL,
  `Klient_IdKlient` INT NOT NULL,
  `Rejestracja` VARCHAR(20) NULL DEFAULT NULL,
  `Czas_rozpoczecia` TIMESTAMP NULL DEFAULT NULL,
  `Czas_zakonczenia` TIMESTAMP NULL DEFAULT NULL,
  `Dodatkowe_informacje` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdAuto`, `Klient_IdKlient`),
  INDEX `fk_Auto_Modele1_idx` (`Modele_IdModele` ASC) VISIBLE,
  INDEX `fk_Auto_Klient1_idx` (`Klient_IdKlient` ASC) VISIBLE,
  CONSTRAINT `fk_Auto_Klient1`
    FOREIGN KEY (`Klient_IdKlient`)
    REFERENCES `db_main`.`Klient` (`IdKlient`),
  CONSTRAINT `fk_Auto_Modele1`
    FOREIGN KEY (`Modele_IdModele`)
    REFERENCES `db_main`.`Modele` (`IdModele`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Pracownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Pracownik` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Pracownik` (
  `IdPracownik` INT NOT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Haslo` VARCHAR(45) NULL DEFAULT NULL,
  `Imie` VARCHAR(45) NULL DEFAULT NULL,
  `Nazwisko` VARCHAR(45) NULL DEFAULT NULL,
  `Telefon` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPracownik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Auto_Pracownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Auto_Pracownik` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Auto_Pracownik` (
  `Pracownik_IdPracownik` INT NOT NULL,
  `Auto_IdAuto` INT NOT NULL,
  PRIMARY KEY (`Pracownik_IdPracownik`, `Auto_IdAuto`),
  INDEX `fk_Pracownik_has_Auto_Auto1_idx` (`Auto_IdAuto` ASC) VISIBLE,
  INDEX `fk_Pracownik_has_Auto_Pracownik1_idx` (`Pracownik_IdPracownik` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_has_Auto_Auto1`
    FOREIGN KEY (`Auto_IdAuto`)
    REFERENCES `db_main`.`Auto` (`IdAuto`),
  CONSTRAINT `fk_Pracownik_has_Auto_Pracownik1`
    FOREIGN KEY (`Pracownik_IdPracownik`)
    REFERENCES `db_main`.`Pracownik` (`IdPracownik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Usluga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Usluga` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Usluga` (
  `IdUsluga` INT NOT NULL,
  `Opis` VARCHAR(45) NULL DEFAULT NULL,
  `Nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUsluga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Auto_Usługa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Auto_Usługa` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Auto_Usługa` (
  `Auto_IdAuto` INT NOT NULL,
  `Usługa_IdUsluga` INT NOT NULL,
  PRIMARY KEY (`Auto_IdAuto`, `Usługa_IdUsluga`),
  INDEX `fk_Auto_has_Usługa_Usługa1_idx` (`Usługa_IdUsluga` ASC) VISIBLE,
  INDEX `fk_Auto_has_Usługa_Auto1_idx` (`Auto_IdAuto` ASC) VISIBLE,
  CONSTRAINT `fk_Auto_has_Usługa_Auto1`
    FOREIGN KEY (`Auto_IdAuto`)
    REFERENCES `db_main`.`Auto` (`IdAuto`),
  CONSTRAINT `fk_Auto_has_Usługa_Usługa1`
    FOREIGN KEY (`Usługa_IdUsluga`)
    REFERENCES `db_main`.`Usluga` (`IdUsluga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Grafik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Grafik` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Grafik` (
  `IdGrafik` INT NOT NULL,
  `Pracownik_IdPracownik` INT NOT NULL,
  `Klient_IdKlient` INT NOT NULL,
  `Czas_rozpoczecia` TIMESTAMP NULL,
  `Czas_zakonczenia` TIMESTAMP NULL,
  PRIMARY KEY (`IdGrafik`, `Klient_IdKlient`),
  INDEX `fk_Grafik_Pracownik_idx` (`Pracownik_IdPracownik` ASC) VISIBLE,
  INDEX `fk_Grafik_Klient1_idx` (`Klient_IdKlient` ASC) VISIBLE,
  CONSTRAINT `fk_Grafik_Klient1`
    FOREIGN KEY (`Klient_IdKlient`)
    REFERENCES `db_main`.`Klient` (`IdKlient`),
  CONSTRAINT `fk_Grafik_Pracownik`
    FOREIGN KEY (`Pracownik_IdPracownik`)
    REFERENCES `db_main`.`Pracownik` (`IdPracownik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Umowa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Umowa` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Umowa` (
  `IdUmowa` INT NOT NULL,
  `Klient_IdKlient` INT NOT NULL,
  `Data_rozpoczecia` DATE NULL,
  `Data_zakonczenia` DATE NULL,
  PRIMARY KEY (`IdUmowa`),
  INDEX `fk_Umowa_Klient1_idx` (`Klient_IdKlient` ASC) VISIBLE,
  CONSTRAINT `fk_Umowa_Klient1`
    FOREIGN KEY (`Klient_IdKlient`)
    REFERENCES `db_main`.`Klient` (`IdKlient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Wersja_umowy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Wersja_umowy` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Wersja_umowy` (
  `Usługa_IdUsluga` INT NOT NULL,
  `Umowa_IdUmowa` INT NOT NULL,
  `Cena` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Usługa_IdUsluga`, `Umowa_IdUmowa`),
  INDEX `fk_Usługa_has_Umowa_Umowa1_idx` (`Umowa_IdUmowa` ASC) VISIBLE,
  INDEX `fk_Usługa_has_Umowa_Usługa1_idx` (`Usługa_IdUsluga` ASC) VISIBLE,
  CONSTRAINT `fk_Usługa_has_Umowa_Umowa1`
    FOREIGN KEY (`Umowa_IdUmowa`)
    REFERENCES `db_main`.`Umowa` (`IdUmowa`),
  CONSTRAINT `fk_Usługa_has_Umowa_Usługa1`
    FOREIGN KEY (`Usługa_IdUsluga`)
    REFERENCES `db_main`.`Usluga` (`IdUsluga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_main`.`Zgloszenie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_main`.`Zgloszenie` ;

CREATE TABLE IF NOT EXISTS `db_main`.`Zgloszenie` (
  `IdZgloszenie` INT NOT NULL,
  `Pracownik_IdPracownik` INT NOT NULL,
  `Klient_IdKlient` INT NOT NULL,
  `Opis` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdZgloszenie`),
  INDEX `fk_Żądanie_Pracownik1_idx` (`Pracownik_IdPracownik` ASC) VISIBLE,
  INDEX `fk_Żądanie_Klient1_idx` (`Klient_IdKlient` ASC) VISIBLE,
  CONSTRAINT `fk_Żądanie_Klient1`
    FOREIGN KEY (`Klient_IdKlient`)
    REFERENCES `db_main`.`Klient` (`IdKlient`),
  CONSTRAINT `fk_Żądanie_Pracownik1`
    FOREIGN KEY (`Pracownik_IdPracownik`)
    REFERENCES `db_main`.`Pracownik` (`IdPracownik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
